### ISSUE TITLE
Police customization

### ISSUE THREAD

**Issue by gsrp-blueberrypie** [gsrp-sheldon/GSRP-CAD-Testing#15]
I ran my own police identity in CAD and noticed that when police officer runs another police officer they comeback as without drivers license/gun license etc and it doesnt say they are cops.
Meaning that if as an undercover catt officer I will give my characters name, I will get arrested for driving without license etc.

**Comment by gsrp-sheldon** [comment]
If undercover you should have a Civ name.

**Comment by gsrp-sheldon** [comment]
I have added the ability to see if someone is Law Enforcement.
